# Generated by Django 4.2.3 on 2023-07-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacationplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planvacations',
            name='image',
            field=models.ImageField(upload_to='vacations_images/'),
        ),
    ]
