# Generated by Django 4.2.3 on 2023-07-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('qualification', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('price', models.IntegerField(default=0)),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
