# Generated by Django 4.2.3 on 2023-07-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='image',
            field=models.ImageField(null=True, upload_to='travel_images/'),
        ),
    ]
